### ISSUE TITLE
Buying moneys & Unban Ticket in shop 

### ISSUE THREAD

**Issue by Mikeofwind** [PurelyAliyah/Outsider#68]
we should able to buy moneys by the shop like in other servers which you can have moneys by buying in the shop 

Also a unban ticket in shop would be nice as a other way to get unban

**Comment by ZephyrXZ** [comment]
Buying an unban just doesnt seem fair, If you get punished, you get punished. There is no fairness in buying yourself unbanned. that will just lead to trolls with money to cause trouble just to buy an unban. and buying money in shop. kinda ruins the vanilla aspect of the game if you ask me. The point of survival is to work your way up. to actually have to work for your things instead of just buying everything. it ruins the survival/vanilla aspect of minecraft. Thats all i have to say.
