### ISSUE TITLE
Ranks Suggestion

### ISSUE THREAD

**Issue by Noorra** [PurelyAliyah/Outsider#72]
Twitch Rank: Those streaming on Twitch on the outsider craft server with 10 followers at minimum get a twitch rank (Like a suffix)
YT Rank: Those recording or livestreaming using YT on the outsider craft server with 50 subscribers or higher get a YT rank (like a suffix)

**Comment by PurelyAliyah** [comment]
We don't this because people who are maknig Youtube ranks and are small youtubers shouldn't be begging for different things, I believe in working your way up, I find these to be cheaty because now a days it doesn't take much to get a few followers or subscribers. I know this because you are literally able to just go around youtube comments make funny comments and get subscribers, It wouldn't be fair to get a rank or perks that way as well as the fact I don't appericate people who are constantly spamming to watch their stream or video it ruins the atmosphere of the server and I also think ranks like that are another way of selling out. 

Please note that I'm not shooting the idea down becasue I'm trying to be rude or anything like that I'm trying to go into details about why I refuse to do it as a Server Owner, Everyone runs their servers differently, Some ranks work for some servers, Some ranks work for other servers but it doesn't always work for every server.

**Comment by Noorra** [comment]
I understand it, your not being rude just wondered why its not a thing but now I know. Thanks
